#!/bin/bash

corPadrao="\033[0m"
preto="\033[0;30m"
vermelho="\033[0;31m"
verde="\033[0;32m"
marrom="\033[0;33m"
azul="\033[0;34m"
purple="\033[0;35m"
cyan="\033[0;36m"
cinzaClaro="\033[0;37m"
pretoCinza="\033[1;30m"
vermelhoClaro="\033[1;31m"
verdeClaro="\033[1;32m"
amarelo="\033[1;33m"
azulClaro="\033[1;34m"
purpleClaro="\033[1;35m"
cyanClaro="\033[1;36m"
branco="\033[1;37m"



echo ""
echo -e "\033[1;32m  BEM VINDO AS CONFIGURAÇÕES DE SEU SERVIDOR:"
echo -e 
echo -e "\033[1;37m(01) Quer configurar sua VPS/SQUID3?"
echo -e "\033[01;31m(02) Vamos Criar um usuarios SSH?"
echo -e "\033[1;37m(03) Que tal fazer Backup dos Usuarios SSH?"
echo -e "\033[01;31m(04) Monitore o Uso da CPU, RAM e UPTIME"
echo -e "\033[1;37m(05) Quer quantos usuários estão Conectados?"
echo -e "\033[01;31m(06) Aquí você Monitora o Uso de Dados/Banda > Enviados & Recebidos"
echo -e "\033[01;31m(07) Vamos fazer uma faxina? Limpa Cache e Swap de seu Servidor"
echo -e "\033[1;37m(08) Liberar a Porta UDP para Ligacão e Jogos no" "\033[1;33m==>>OpenVPN"
echo -e "\033[01;31m(09) Testar a Velocidade de Link do Servidor" "\033[1;33m==>> OpenVPN ou VPS/SSH"
echo -e "\033[1;37m(10) Mensagem de banner SSH para quando os Usuarios se Conectar"
echo -e "\033[01;31m(11) Limita as Conexoes de Cada Usuario"
echo -e "\033[1;37m(12) Muda o Limite do Usuario"
echo -e "\033[01;31m(13) Altere a Senha dos Usuarios"
echo -e "\033[1;37m(14) Mude a Data de Validade de seus Usuarios"
echo -e "\033[01;31m(15) Exluir Usuarios"
echo -e "\033[1;37m(16) Adicione um Novo Host ao Squid"
echo -e "\033[01;31m(17) Configura e Gerencia Usuarios no" "\033[1;33m==>>OpenVPN"
echo -e "\033[1;37m(18) Limpar Usuarios Vencidos"
echo -e "\033[01;31m(19) Procure ATT para Kernel ou Remove\033[1;32m"
echo -e "\033[1;37m(20) Ver usuário conectados"  "\033[1;33m==>>OpenVPN"y
echo""
read -p " O QUE DESEJA FAZER? ESCOLHA UMA DAS OPÇÕES DE [01-20]: " opcao

case $opcao in
 01)
  ConfVPS
  sleep 4
  ajuda;;
 02)
  UserCreate
  sleep 5
  ajuda;;
 03)
  UserBackup
  sleep 5
  ajuda;;
 04)
  CpuMonitor;;
 05)
  UserMonitor;;
 06)
  DadosMonitor;;
 07)
  ClearCache
  sleep 4
  ajuda;;
 08)
  OpenUDP;;
 09)
  SpeedTest
  sleep 15
  ajuda;;
 10)
  Banner
  sleep 4
  ajuda;;
 11)
  LimiterSSH;;
 12)
  MudarLimite
  sleep 4
  ajuda;;
 13)
  MudarSenha
  sleep 4
  ajuda;;
 14)
  MudarValidade
  sleep 5
  ajuda;;
 15)
  UserDel
  sleep 4
  ajuda;;
 16)
  addhost
  sleep 4
  ajuda;;
 17)
  OpenVPN
  sleep 5
  ajuda;;
 18)
  UserClear
  sleep 3
  ajuda;;
 19)
  KernelControl
  sleep 2
  ajuda;;
 20)
  check
  sleep 15
  ajuda;;
esac
